name: Deploy to GitHub Pages
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install requirements
      run: |
        echo "Installing Python3..."
        sudo apt-get install python3-venv
        echo "Setting up virtual environment..."
        python3 -m venv venv
        echo "Activating virtual environment..."
        source venv/bin/activate
        echo "Installing dependencies from requiremens.txt..."
        pip install -r requirements.txt
    - name: Make static
      run: |
        docnado --html public
    - name: Deploy to GitHub Pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: "public/"
        GITHUB_PAGES: ${{ secrets.GITHUB_PAGES }}
